### ISSUE TITLE
How to get a layer by title and add some external js functionalities

### ISSUE THREAD

**Issue by aapopei** [GreenInfo-Network/L.Control.AccordionLegend#13]
You can help me if I can get a layer by the title? I want to add some map click events for specific layers and to check witch one is active (like `map.hasLayer(nameofthelayer)`).
It's something with the function `listLayersStates()`?

**Comment by gregallensworth** [comment]
See the new `getLayer()` and `getLayerState()` methods, in the new 1.2.2 release. https://github.com/GreenInfo-Network/L.Control.AccordionLegend/releases

These should accomplish what you asked for.

**Comment by aapopei** [comment]
Thank you so much for the new methods. I do not know if I'm doing the right thing, but when I call

`if (getLayerState('THIS_IS_THE_TITLE_OF_THE_LAYER') === true) { ... });`

I'm getting the error 

> Uncaught ReferenceError: getLayer is not defined

I initialize the .js and .css of the plugin at the beginning of the HTML page, appears to be loaded into the console, and the methods are called inside the HTML body.

**Comment by aapopei** [comment]
I solved the issue. It was my mistake. I called the `new L.Control.AccordionLegend` inside a variable like this `var lay = new L.Control.AccordionLegend`, and I forgot to call the methods like `lay.getLayerState("LAYER_TITLE")`
Thank you once again. You can close the ticket.
