### ISSUE TITLE
problem with input opacity range on mobile devices

### ISSUE THREAD

**Issue by aapopei** [GreenInfo-Network/L.Control.AccordionLegend#15]
Hi there,

I'm using the latest stable version of the leaflet plugin, and I'm trying to catch the tap/click of the input range opacity. It's frozen! The main accordion control div it works great.
P.S. I tried also to call the latest jquery and jquery.mobile, but still not working.

**Comment by gregallensworth** [comment]
I have an updated version at http://greeninfo-network.github.io/L.Control.AccordionLegend/ which fixes some problems I had on mobile (Firefox for Android). Give this a try on mobile, and let me know how it works for you. If you like it, you can grab the latest version from the **dist/** folder, and I will draft a new release as well.

**Comment by aapopei** [comment]
Thank you very much for your time and knowledge. Everything works fine now on mobile devices, but in the updated version you forgot to add two methods that you added previously:

> getLayer: function (layername) {
>         var layer = this.layerRegistry[layername];
>         return layer;
>     },
> getLayerState: function (layername) {
>         var layer = this.layerRegistry[layername];
>         return this.map.hasLayer(layer);
>     },
