### ISSUE TITLE
Layer symbology not visible

### ISSUE THREAD

**Issue by LewisEllisWooster** [GreenInfo-Network/L.Control.AccordionLegend#4]
Sorry to be a bother but I can't see the legend symbology of the referenced layer. I have copied the content parameter structure for the legend exactly as described in your basic usage notes. I can see the title for the layer and toggle it on and off but that is it.

**Comment by danrademacher** [comment]
Can you include screenshots of what you're seeing and also show any errors in console? Fair warning: we don't have much time to support usage of the open source tools we develop for our client projects, but if we see an easy fix, happy to help.

**Comment by gregallensworth** [comment]
Thank you for mentioning this. I have found the issue, and will be patching it up later today.

**Comment by gregallensworth** [comment]
@LewisEllisWooster Thank you again for reporting this. I've made some improvements to the library (a bug fix), and to the demo (better demonstration of what it does), and to the functionality (now supports *line* as a legend swatch).

Hit up the Releases and grab a new one, to replace the one you're trying now.

**Comment by LewisEllisWooster** [comment]
Thank you gentleman for being so quick to respond. Much appreciated Greg.
